package dsekercioglu.general;

public class Defaults {

    public static final float MARLIN_TURN = 0.08726646F;
    public static final float MARLIN_LENGTH = 140.0F;
    public static final float MARLIN_WEIGHT = 2000.0F;
    public static final float MARLIN_SPEED = 0.1F * 7.0F;
    public static final float MARLIN_PASSIVE_ABILITY = 3.0F;
    public static final float MARLIN_MAX_ENERGY = 3.0F;
    public static final float MARLIN_ENERGY_INCREASE = 0.0025F;
    public static final float MARLIN_MAX_HEALTH = 700;
    public static final float MARLIN_HEALTH_REGEN = 0.5F;
    public static final float MARLIN_DAMAGE = 180F; // 300
    public static final int MARLIN_BOOST_TIME = 50;
    public static final int MARLIN_ABILITY_TIME = 60;

    public static final float BLACK_MARLIN_TURN = 0.08726646F;
    public static final float BLACK_MARLIN_LENGTH = 140.0F;
    public static final float BLACK_MARLIN_WEIGHT = 1650.0F;
    public static final float BLACK_MARLIN_SPEED = 0.1F * 8.0F;
    public static final float BLACK_MARLIN_PASSIVE_ABILITY = 3.0F;
    public static final float BLACK_MARLIN_MAX_ENERGY = 2.0F;
    public static final float BLACK_MARLIN_ENERGY_INCREASE = 0.0025F;
    public static final float BLACK_MARLIN_MAX_HEALTH = 600;
    public static final float BLACK_MARLIN_HEALTH_REGEN = 0.5F;
    public static final float BLACK_MARLIN_DAMAGE = 180F; // 320
    public static final int BLACK_MARLIN_BOOST_TIME = 28;
    public static final int BLACK_MARLIN_ABILITY_TIME = 75;

    public static final float CROCODILE_TURN = 0.08726646F;
    public static final float CROCODILE_LENGTH = 170.0F;
    public static final float CROCODILE_WEIGHT = 2500.0F;
    public static final float CROCODILE_SPEED = 0.1F * 5.1F;
    public static final float CROCODILE_PASSIVE_ABILITY = 2.0F;
    public static final float CROCODILE_MAX_ENERGY = 2.0F;
    public static final float CROCODILE_ENERGY_INCREASE = 0.0025F;
    public static final float CROCODILE_MAX_HEALTH = 1000;
    public static final float CROCODILE_HEALTH_REGEN = 0.5F;
    public static final float CROCODILE_DAMAGE = 120F; // 270
    public static final int CROCODILE_BOOST_TIME = 40;
    public static final int CROCODILE_ABILITY_TIME = 90;

    public static final float SHARK_TURN = 0.045F;
    public static final float SHARK_LENGTH = 170.0F;
    public static final float SHARK_WEIGHT = 3200.0F;
    public static final float SHARK_SPEED = 0.1F * 5.3F;
    public static final float SHARK_PASSIVE_ABILITY = 1.0F;
    public static final float SHARK_MAX_ENERGY = 2.0F;
    public static final float SHARK_ENERGY_INCREASE = 0.0025F;
    public static final float SHARK_MAX_HEALTH = 800;
    public static final float SHARK_HEALTH_REGEN = 0.5F;
    public static final float SHARK_DAMAGE = 160F; // 240
    public static final int SHARK_BOOST_TIME = 120;
    public static final int SHARK_ABILITY_TIME = 0;

    public static final float MEGA_MOUTH_SHARK_TURN = 0.045F;
    public static final float MEGA_MOUTH_SHARK_LENGTH = 170.0F;
    public static final float MEGA_MOUTH_SHARK_WEIGHT = 1600.0F;
    public static final float MEGA_MOUTH_SHARK_SPEED = 0.1F * 5.5F;
    public static final float MEGA_MOUTH_SHARK_PASSIVE_ABILITY = 1.0F;
    public static final float MEGA_MOUTH_SHARK_MAX_ENERGY = 2.0F;
    public static final float MEGA_MOUTH_SHARK_ENERGY_INCREASE = 0.0025F;
    public static final float MEGA_MOUTH_SHARK_MAX_HEALTH = 950;
    public static final float MEGA_MOUTH_SHARK_HEALTH_REGEN = 0.5F;
    public static final float MEGA_MOUTH_SHARK_DAMAGE = 100; //300
    public static final int MEGA_MOUTH_SHARK_BOOST_TIME = 40;
    public static final int MEGA_MOUTH_SHARK_ABILITY_TIME = 150;

    public static final float ORCA_TURN = 0.045F;
    public static final float ORCA_LENGTH = 170.0F;
    public static final float ORCA_WEIGHT = 3200.0F;
    public static final float ORCA_SPEED = 0.1F * 5.6F;
    public static final float ORCA_PASSIVE_ABILITY = 1.0F;
    public static final float ORCA_MAX_ENERGY = 2.0F;
    public static final float ORCA_ENERGY_INCREASE = 0.0025F;
    public static final float ORCA_MAX_HEALTH = 900;
    public static final float ORCA_HEALTH_REGEN = 0.5F;
    public static final float ORCA_DAMAGE = 150F; // 240
    public static final int ORCA_BOOST_TIME = 40;
    public static final int ORCA_ABILITY_TIME = 75;

    public static final float HIPPO_TURN = 0.06F;
    public static final float HIPPO_LENGTH = 165.0F;
    public static final float HIPPO_WEIGHT = 7000.0F;
    public static final float HIPPO_SPEED = 0.1F * 5.5F;
    public static final float HIPPO_PASSIVE_ABILITY = 2.0F;
    public static final float HIPPO_MAX_ENERGY = 2.0F;
    public static final float HIPPO_ENERGY_INCREASE = 0.0025F;
    public static final float HIPPO_MAX_HEALTH = 1000;
    public static final float HIPPO_HEALTH_REGEN = 0.5F;
    public static final float HIPPO_DAMAGE = 100F; // 400
    public static final int HIPPO_BOOST_TIME = 1000;
    public static final int HIPPO_ABILITY_TIME = 0;

    public static final float COLOSSAL_SQUID_TURN = 0.08726646F;
    public static final float COLOSSAL_SQUID_LENGTH = 50.0F;
    public static final float COLOSSAL_SQUID_WEIGHT = 1000.0F;
    public static final float COLOSSAL_SQUID_SPEED = 0.1F * 4.8F;
    public static final float COLOSSAL_SQUID_PASSIVE_ABILITY = 2.0F;
    public static final float COLOSSAL_SQUID_MAX_ENERGY = 3.0F;
    public static final float COLOSSAL_SQUID_ENERGY_INCREASE = 0.0025F;
    public static final float COLOSSAL_SQUID_MAX_HEALTH = 550;
    public static final float COLOSSAL_SQUID_HEALTH_REGEN = 0.5F;
    public static final float COLOSSAL_SQUID_DAMAGE = 120F; // 120
    public static final int COLOSSAL_SQUID_BOOST_TIME = 75;
    public static final int COLOSSAL_SQUID_ABILITY_TIME = 48;

    public static final float DOOD_FISH_TURN = 0.12F;
    public static final float DOOD_FISH_LENGTH = 90.0F;
    public static final float DOOD_FISH_WEIGHT = 600.0F;
    public static final float DOOD_FISH_SPEED = 0.1F * 6.2F;
    public static final float DOOD_FISH_PASSIVE_ABILITY = 2.0F;
    public static final float DOOD_FISH_MAX_ENERGY = 2.0F;
    public static final float DOOD_FISH_ENERGY_INCREASE = 0.0025F;
    public static final float DOOD_FISH_MAX_HEALTH = 400;
    public static final float DOOD_FISH_HEALTH_REGEN = 0.5F;
    public static final float DOOD_FISH_DAMAGE = 100; //210
    public static final int DOOD_FISH_BOOST_TIME = 600;
    public static final int DOOD_FISH_ABILITY_TIME = 70;

    public static final float ELECTRIC_MARLIN_TURN = 0.16F;
    public static final float ELECTRIC_MARLIN_LENGTH = 140.0F;
    public static final float ELECTRIC_MARLIN_WEIGHT = 1350.0F;
    public static final float ELECTRIC_MARLIN_SPEED = 0.1F * 9.0F;
    public static final float ELECTRIC_MARLIN_PASSIVE_ABILITY = 3.0F;
    public static final float ELECTRIC_MARLIN_MAX_ENERGY = 3.0F;
    public static final float ELECTRIC_MARLIN_ENERGY_INCREASE = 0.0025F;
    public static final float ELECTRIC_MARLIN_MAX_HEALTH = 500;
    public static final float ELECTRIC_MARLIN_HEALTH_REGEN = 0.5F;
    public static final float ELECTRIC_MARLIN_DAMAGE = 180F; // 320
    public static final int ELECTRIC_MARLIN_BOOST_TIME = 50;
    public static final int ELECTRIC_MARLIN_ABILITY_TIME = 40;

    public static final float SHARKODILE_TURN = 0.045F;
    public static final float SHARKODILE_LENGTH = 200.0F;
    public static final float SHARKODILE_WEIGHT = 4000.0F;
    public static final float SHARKODILE_SPEED = 0.1F * 5.2F;
    public static final float SHARKODILE_PASSIVE_ABILITY = 3.0F;
    public static final float SHARKODILE_MAX_ENERGY = 5.0F;
    public static final float SHARKODILE_ENERGY_INCREASE = 0.005F;
    public static final float SHARKODILE_MAX_HEALTH = 1200;
    public static final float SHARKODILE_HEALTH_REGEN = 2F;
    public static final float SHARKODILE_DAMAGE = 170F;
    public static final int SHARKODILE_BOOST_TIME = 60;
    public static final int SHARKODILE_ABILITY_TIME = 100;

    public static final float MARLINIUM_TURN = 0.1F;
    public static final float MARLINIUM_LENGTH = 140.0F;
    public static final float MARLINIUM_WEIGHT = 4000.0F;
    public static final float MARLINIUM_SPEED = 0.1F * 7.0F;
    public static final float MARLINIUM_PASSIVE_ABILITY = 3.0F;
    public static final float MARLINIUM_MAX_ENERGY = 2.0F;
    public static final float MARLINIUM_ENERGY_INCREASE = 0.002F;
    public static final float MARLINIUM_MAX_HEALTH = 900;
    public static final float MARLINIUM_HEALTH_REGEN = 1F;
    public static final float MARLINIUM_DAMAGE = 200F;
    public static final int MARLINIUM_BOOST_TIME = 60;
    public static final int MARLINIUM_ABILITY_TIME = 100;

    public static final float MINI_MARLIN_TURN = 0.08726646F;
    public static final float MINI_MARLIN_LENGTH = 100.0F;
    public static final float MINI_MARLIN_WEIGHT = 1000.0F;
    public static final float MINI_MARLIN_SPEED = 0.1F * 8.0F;
    public static final float MINI_MARLIN_PASSIVE_ABILITY = 3.0F;
    public static final float MINI_MARLIN_MAX_ENERGY = 2.0F;
    public static final float MINI_MARLIN_ENERGY_INCREASE = 0.005F;
    public static final float MINI_MARLIN_MAX_HEALTH = 100;
    public static final float MINI_MARLIN_HEALTH_REGEN = 0.5F;
    public static final float MINI_MARLIN_DAMAGE = 50F;
    public static final int MINI_MARLIN_BOOST_TIME = 40;
    public static final int MINI_MARLIN_ABILITY_TIME = 50;

    public static final float TIGER_SHARK_TURN = 0.1F;
    public static final float TIGER_SHARK_LENGTH = 140.0F;
    public static final float TIGER_SHARK_WEIGHT = 1500.0F;
    public static final float TIGER_SHARK_SPEED = 0.1F * 6F;
    public static final float TIGER_SHARK_PASSIVE_ABILITY = 1.0F;
    public static final float TIGER_SHARK_MAX_ENERGY = 3.0F;
    public static final float TIGER_SHARK_ENERGY_INCREASE = 0.0025F;
    public static final float TIGER_SHARK_MAX_HEALTH = 750;
    public static final float TIGER_SHARK_HEALTH_REGEN = 0.5F;
    public static final float TIGER_SHARK_DAMAGE = 160F; // 300
    public static final int TIGER_SHARK_BOOST_TIME = 60;
    public static final int TIGER_SHARK_ABILITY_TIME = 4;

    public static final float DOLPHIN_TURN = 0.1F;
    public static final float DOLPHIN_LENGTH = 140.0F;
    public static final float DOLPHIN_WEIGHT = 1500.0F;
    public static final float DOLPHIN_SPEED = 0.1F * 5.7F;
    public static final float DOLPHIN_PASSIVE_ABILITY = 1.0F;
    public static final float DOLPHIN_MAX_ENERGY = 3.0F;
    public static final float DOLPHIN_ENERGY_INCREASE = 0.0025F;
    public static final float DOLPHIN_MAX_HEALTH = 640;
    public static final float DOLPHIN_HEALTH_REGEN = 0.5F;
    public static final float DOLPHIN_DAMAGE = 135F; // 200
    public static final int DOLPHIN_BOOST_TIME = 140;
    public static final int DOLPHIN_ABILITY_TIME = 0;

    public static final float MAKO_SHARK_TURN = 0.1F;
    public static final float MAKO_SHARK_LENGTH = 140.0F;
    public static final float MAKO_SHARK_WEIGHT = 1500.0F;
    public static final float MAKO_SHARK_SPEED = 0.1F * 7F;
    public static final float MAKO_SHARK_PASSIVE_ABILITY = 1.0F;
    public static final float MAKO_SHARK_MAX_ENERGY = 3.0F;
    public static final float MAKO_SHARK_ENERGY_INCREASE = 0.0025F;
    public static final float MAKO_SHARK_MAX_HEALTH = 650;
    public static final float MAKO_SHARK_HEALTH_REGEN = 0.75F;
    public static final float MAKO_SHARK_DAMAGE = 160F; // 320
    public static final int MAKO_SHARK_BOOST_TIME = 50;
    public static final int MAKO_SHARK_ABILITY_TIME = 32;

    public static final float TWO_RULERS_TURN = 0.1F;
    public static final float TWO_RULERS_LENGTH = 100.0F;
    public static final float TWO_RULERS_WEIGHT = 1500.0F;
    public static final float TWO_RULERS_SPEED = 0.1F * 5.5F;
    public static final float TWO_RULERS_PASSIVE_ABILITY = 1.0F;
    public static final float TWO_RULERS_MAX_ENERGY = 3.0F;
    public static final float TWO_RULERS_ENERGY_INCREASE = 0.0025F;
    public static final float TWO_RULERS_MAX_HEALTH = 400;
    public static final float TWO_RULERS_HEALTH_REGEN = 1F;
    public static final float TWO_RULERS_DAMAGE = 80; //120
    public static final int TWO_RULERS_BOOST_TIME = 50;
    public static final int TWO_RULERS_ABILITY_TIME = 150;

    public static final float GUARDIAN_TURN = 0.045F;
    public static final float GUARDIAN_LENGTH = 90.0F;
    public static final float GUARDIAN_WEIGHT = 3000.0F;
    public static final float GUARDIAN_SPEED = 0.1F * 4.0F;
    public static final float GUARDIAN_PASSIVE_ABILITY = 3.0F;
    public static final float GUARDIAN_MAX_ENERGY = 1.0F;
    public static final float GUARDIAN_ENERGY_INCREASE = 0.0025F;
    public static final float GUARDIAN_MAX_HEALTH = 1200;
    public static final float GUARDIAN_HEALTH_REGEN = 1.5F;
    public static final float GUARDIAN_DAMAGE = 60F;
    public static final int GUARDIAN_BOOST_TIME = 1000;
    public static final int GUARDIAN_ABILITY_TIME = 30;

    public static final float GHOST_TURN = 1.58F;
    public static final float GHOST_LENGTH = 80.0F;
    public static final float GHOST_WEIGHT = 0.0F;
    public static final float GHOST_SPEED = 0.1F * 9.0F;
    public static final float GHOST_PASSIVE_ABILITY = 3.0F;
    public static final float GHOST_MAX_ENERGY = 3.0F;
    public static final float GHOST_ENERGY_INCREASE = GHOST_MAX_ENERGY;
    public static final float GHOST_MAX_HEALTH = 1;
    public static final float GHOST_HEALTH_REGEN = 0;
    public static final float GHOST_DAMAGE = 0;
    public static final int GHOST_BOOST_TIME = 3;
    public static final int GHOST_ABILITY_TIME = 0;

}
