package dsekercioglu.general.characters;

public enum Ability {
//    BLEED, KNOCKBACK, HOLD, SHOCK, STICK, DRAIN_GRAB, GRAB, SUPERBITE, INKSPILL,
//    POISON, PRISON, REGEN_BOOST, DRAIN_HIT, DAMAGE_BOOST, SLOW_DOWN, HORN
      BLEED, KNOCKBACK, HOLD, SHOCK, STICK, GRAB, SUPERBITE, INKSPILL, POISON, PRISON, REGEN, DRAIN, SLOW_DOWN, HORN, REGEN_GRAB, SHORT_GRAB
}
