package dsekercioglu.general.characters;

public enum Ability {
      BLEED, KNOCKBACK, HOLD, SHOCK, STICK, GRAB, SUPERBITE, INKSPILL, POISON,
      PRISON, REGEN, DRAIN, SLOW_DOWN, HORN, REGEN_GRAB, SHORT_GRAB,
      ELECTRIC_HORN, BLEEDING_KNOCKBACK
}
