package dsekercioglu.general.characters;

public enum Animal {
    MARLIN, BLACK_MARLIN, CROCODILE, SHARK, ELECTRIC_EEL, BARRACUDA, MEGA_MOUTH, ORCA, HIPPO, COLOSSAL_SQUID, DOOD_FISH, ELECTRIC_MARLIN, ORCA_AI, SHARK_AI, HIPPO_AI
}
