package dsekercioglu.general.characters;

public enum Animal {
    MARLIN, BLACK_MARLIN, CROCODILE, SHARK, ELECTRIC_EEL, BARRACUDA, MEGA_MOUTH,
    ORCA, HIPPO, COLOSSAL_SQUID, DOOD_FISH, ELECTRIC_MARLIN, GUARDIAN, TIGER_SHARK, DOLPHIN, SHARKODILE,
    MARLINIUM, MINI_MARLIN, ANGLERAPTOR
}
